services:
  api:
    build: .
    container_name: device-financing-api
    restart: always
    ports:
      - "${API_HOST_PORT:-3001}:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: node dist/main.js
    volumes:
      - .:/app

  worker:
    build: .
    container_name: device-financing-worker
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: yarn worker

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
