// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isPrismaGenerateCommand = process.argv.some(
  (arg) => arg === "generate" || arg.endsWith(":generate"),
);
const databaseUrl = process.env["DATABASE_URL"]?.trim();
const fallbackDatabaseUrl =
  "postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public";

if (
  (!databaseUrl || databaseUrl === "\"\"" || databaseUrl === "''") &&
  !isPrismaGenerateCommand
) {
  throw new Error("DATABASE_URL must be set for Prisma commands.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl || fallbackDatabaseUrl,
  },
});
